-- +goose Up

-- Daily payout batching + the cost of a payout (owner decisions, 25.07.2026).
--
-- Two things this migration adds to the payout module:
--
-- 1. ONE PAYOUT PER VENUE PER DAY. Payouts are now produced by a scheduled
--    end-of-day pass, not on demand, and the day is the VENUE's local day
--    (restaurants.timezone), not the server's. `period_date` is that local
--    calendar day and a partial UNIQUE index makes "pay the same venue twice
--    for the same day" a database error rather than a code convention.
--
-- 2. THE PAYOUT COSTS MONEY. FreedomPay's tariff (merchant questionnaire,
--    14.07.2026) charges 1.9% with a MINIMUM of 300 ₸ for a payout to a KZ
--    bank card. Until now that cost existed nowhere in the system. It is now
--    an explicit, frozen-at-generation column on every payout, plus its own
--    double-entry ledger, so "what did paying our venues cost us last month"
--    is a SUM, not an estimate.
--
-- Safe on a populated table: every added column is nullable or has a DEFAULT,
-- the backfill is a single UPDATE over existing rows, and the new UNIQUE index
-- only constrains rows that carry a period_date — i.e. none of the historical
-- ones.

ALTER TABLE payouts
    -- Money claimed into the payout, BEFORE the acquirer's payout fee. Equals
    -- the sum of the payout's items. `amount_minor` stays what is actually
    -- dispatched to the venue: equal to the gross when the platform absorbs the
    -- fee (the default), gross - fee when the venue bears it.
    ADD COLUMN gross_amount_minor bigint      NOT NULL DEFAULT 0,
    -- What the acquirer charges us to move this payout, computed at generation
    -- from the configured rate + floor and frozen here: a later tariff change
    -- must never rewrite what a past payout cost.
    ADD COLUMN fee_minor          bigint      NOT NULL DEFAULT 0,
    -- Who paid fee_minor for THIS payout, snapshotted from the policy in force
    -- when it was generated. 'platform' is the safe default: the venue always
    -- receives exactly what its statement said it was owed.
    ADD COLUMN fee_bearer         varchar     NOT NULL DEFAULT 'platform',
    -- The VENUE-LOCAL calendar day whose end-of-day this payout settles. NULL
    -- for a payout generated by hand outside the schedule — those consume no
    -- day and are deliberately not constrained by the once-per-day index.
    ADD COLUMN period_date        date,
    -- The exact instant that local day ended. Ledger entries created strictly
    -- before it are in scope. There is no period_start_at on purpose: the lower
    -- bound of a payout is "not yet claimed", not a date, so money rolled over
    -- from an earlier day is picked up here without carry-forward bookkeeping.
    ADD COLUMN period_end_at      timestamptz;

-- Backfill: every pre-existing payout was generated before the fee existed, so
-- its gross equals the amount that was sent and its fee is genuinely zero. Not
-- an estimate — those payouts really did not have a modelled fee.
UPDATE payouts SET gross_amount_minor = amount_minor WHERE gross_amount_minor = 0;

ALTER TABLE payouts
    ADD CONSTRAINT chk_payouts_gross_positive CHECK (gross_amount_minor > 0),
    ADD CONSTRAINT chk_payouts_fee_non_negative CHECK (fee_minor >= 0),
    ADD CONSTRAINT chk_payouts_fee_bearer CHECK (fee_bearer IN ('platform', 'venue')),
    -- A period_date and its end instant travel together or not at all.
    ADD CONSTRAINT chk_payouts_period_pair
        CHECK ((period_date IS NULL) = (period_end_at IS NULL));

-- THE once-per-venue-per-day guarantee, enforced by the database.
--
-- Partial on `status <> 'failed'` on purpose, and this is the whole design:
--   * a pending / sent / paid payout OWNS the venue's day — a second worker
--     tick, a restarted worker or a second worker instance racing the first
--     hits a unique violation and skips, so a venue can never be paid twice for
--     the same period;
--   * a FAILED payout releases its claimed ledger entries (payout_items are
--     deleted) and, by dropping out of this index, releases the day too — a
--     failed send must not consume the period, otherwise a declined payout
--     would silently postpone the venue's money by a day.
-- NULL period_date rows (manual payouts) are unconstrained: NULLs are distinct.
CREATE UNIQUE INDEX uq_payouts_venue_period
    ON payouts (restaurant_id, currency, period_date)
    WHERE status <> 'failed';

-- The daily pass reads "has this venue already been paid for this day"; the
-- index above serves that too, so no extra one is added.

CREATE TABLE payout_ledger_entries
(
    id           uuid PRIMARY KEY,
    payout_id    uuid        NOT NULL REFERENCES payouts (id) ON DELETE CASCADE,
    -- Same account vocabulary as payment_ledger_entries: guest / restaurant /
    -- platform / acquirer. A payout books restaurant->acquirer for the money
    -- and <bearer>->acquirer for the fee.
    account      varchar     NOT NULL,
    direction    varchar     NOT NULL,
    -- Always positive; direction, not sign, carries the meaning.
    amount_minor bigint      NOT NULL,
    currency     varchar     NOT NULL,
    -- 'settlement' for the money, 'payout_fee' for the acquirer's charge.
    -- payout_fee is deliberately distinct from the payment ledger's
    -- 'acquiring', which is the cut withheld on the money-IN side.
    entry_type   varchar     NOT NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT chk_payout_ledger_account
        CHECK (account IN ('guest', 'restaurant', 'platform', 'acquirer')),
    CONSTRAINT chk_payout_ledger_direction
        CHECK (direction IN ('debit', 'credit')),
    CONSTRAINT chk_payout_ledger_amount_positive CHECK (amount_minor > 0),
    -- Append-only AND replay-safe: a retried "mark this payout paid" cannot
    -- book the same cost a second time. The status CAS already admits one
    -- winner; this is the DB-level second line of defence.
    CONSTRAINT uq_payout_ledger_line UNIQUE (payout_id, account, direction, entry_type)
);

CREATE INDEX idx_payout_ledger_payout ON payout_ledger_entries (payout_id);
-- Reporting: "what did payouts cost us in period X, and who paid".
CREATE INDEX idx_payout_ledger_type ON payout_ledger_entries (entry_type, account, created_at);

-- +goose Down
DROP TABLE payout_ledger_entries;
DROP INDEX uq_payouts_venue_period;
ALTER TABLE payouts
    DROP CONSTRAINT chk_payouts_period_pair,
    DROP CONSTRAINT chk_payouts_fee_bearer,
    DROP CONSTRAINT chk_payouts_fee_non_negative,
    DROP CONSTRAINT chk_payouts_gross_positive,
    DROP COLUMN period_end_at,
    DROP COLUMN period_date,
    DROP COLUMN fee_bearer,
    DROP COLUMN fee_minor,
    DROP COLUMN gross_amount_minor;
