package payouts

import (
	"time"

	"backend-core/internal/domain"
	uc "backend-core/internal/usecase/payouts"
)

// destinationRequest sets a restaurant's payout destination. A raw PAN is never
// accepted — token is a provider card token (UUID); the usecase rejects
// anything PAN-shaped.
type destinationRequest struct {
	Method              string `json:"method"`
	Token               string `json:"token"`
	ProviderCustomerRef string `json:"provider_customer_ref"`
	MaskedIdentifier    string `json:"masked_identifier"`
}

func (r destinationRequest) toInput() uc.DestinationInput {
	return uc.DestinationInput{
		Method:              domain.PayoutMethod(r.Method),
		Token:               r.Token,
		ProviderCustomerRef: r.ProviderCustomerRef,
		MaskedIdentifier:    r.MaskedIdentifier,
	}
}

type destinationResponse struct {
	RestaurantID     string    `json:"restaurant_id"`
	Provider         string    `json:"provider"`
	Method           string    `json:"method"`
	MaskedIdentifier string    `json:"masked_identifier"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

// destinationToResponse deliberately OMITS the token and the provider customer
// ref: they are the address of the money and never need to leave the server in
// a read response. The masked identifier is the venue-facing hint.
func destinationToResponse(d *domain.PayoutDestination) destinationResponse {
	return destinationResponse{
		RestaurantID:     d.RestaurantID.String(),
		Provider:         string(d.Provider),
		Method:           string(d.Method),
		MaskedIdentifier: d.MaskedIdentifier,
		CreatedAt:        d.CreatedAt,
		UpdatedAt:        d.UpdatedAt,
	}
}

// payoutResponse is one line of a venue's statement. It exposes all THREE
// amounts, not just the transferred one, so "we were owed X but Y arrived" is
// answerable from the statement itself instead of from support:
//
//	gross_amount_minor — settled money for the period, before the payout fee
//	fee_minor          — what moving it cost at the acquirer
//	fee_bearer         — who paid that cost ("platform" = the venue's amount is
//	                     untouched; "venue" = it was deducted here)
//	amount_minor       — what was actually transferred
type payoutResponse struct {
	ID               string `json:"id"`
	RestaurantID     string `json:"restaurant_id"`
	AmountMinor      int64  `json:"amount_minor"`
	GrossAmountMinor int64  `json:"gross_amount_minor"`
	FeeMinor         int64  `json:"fee_minor"`
	FeeBearer        string `json:"fee_bearer"`
	// PeriodDate is the venue-local day this payout settled, "YYYY-MM-DD".
	// Absent for a payout generated by hand outside the daily schedule.
	PeriodDate        *string    `json:"period_date,omitempty"`
	Currency          string     `json:"currency"`
	Status            string     `json:"status"`
	ProviderRef       *string    `json:"provider_ref,omitempty"`
	FailureReason     *string    `json:"failure_reason,omitempty"`
	NeedsManualReview bool       `json:"needs_manual_review"`
	SentAt            *time.Time `json:"sent_at,omitempty"`
	PaidAt            *time.Time `json:"paid_at,omitempty"`
	CreatedAt         time.Time  `json:"created_at"`
}

func payoutToResponse(p domain.Payout) payoutResponse {
	var period *string
	if p.PeriodDate != nil {
		d := p.PeriodDate.Format(time.DateOnly)
		period = &d
	}
	return payoutResponse{
		ID:                p.ID.String(),
		RestaurantID:      p.RestaurantID.String(),
		AmountMinor:       p.AmountMinor,
		GrossAmountMinor:  p.GrossAmountMinor,
		FeeMinor:          p.FeeMinor,
		FeeBearer:         string(p.FeeBearer),
		PeriodDate:        period,
		Currency:          string(p.Currency),
		Status:            string(p.Status),
		ProviderRef:       p.ProviderRef,
		FailureReason:     p.FailureReason,
		NeedsManualReview: p.NeedsManualReview,
		SentAt:            p.SentAt,
		PaidAt:            p.PaidAt,
		CreatedAt:         p.CreatedAt,
	}
}

func payoutsToResponse(list []domain.Payout) []payoutResponse {
	out := make([]payoutResponse, 0, len(list))
	for _, p := range list {
		out = append(out, payoutToResponse(p))
	}
	return out
}
